name: 'ShellCheck'
run-name: ${{ github.workflows }} is testing ${{ github.actor }} push 🚀
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: azohra/shell-linter@latest
        with:
              path: "02_Desktop_search/import_spbu_umd.sh" 
